#!/bin/sh
set -e
lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --binary-images iso-hybrid \
  --apt-recommends true \
  --firmware-chroot true \
  --firmware-binary true \
  --source false \
  --iso-application "debwin" \
  --iso-publisher "debwin contributors" \
  --iso-volume "DEBWIN"
